#ifndef AON_CONSTANTS_HPP_
#define AON_CONSTANTS_HPP_

#define BRAIN_SCREEN_WIDTH 480
#define BRAIN_SCREEN_HEIGHT 240

// NOT using 15 inch robot = Using 18 inch robot
#define USING_15_INCH_ROBOT true

#if USING_15_INCH_ROBOT

#define DRIVE_WHEEL_DIAMETER 2.75
#define TRACKING_WHEEL_DIAMETER 1.9644
#define DEGREES_PER_REVOLUTION 360.0
#define INITIAL_ODOMETRY_X 0.0
#define INITIAL_ODOMETRY_Y 0.0
#define INITIAL_ODOMETRY_THETA 0.0
#define DISTANCE_LEFT_TRACKING_WHEEL_CENTER 4.0
#define DISTANCE_RIGHT_TRACKING_WHEEL_CENTER 4.0
#define DISTANCE_BACK_TRACKING_WHEEL_CENTER 3.75
#define GYRO_ENABLED true
#define GYRO_CONFIDENCE 1.0
#define GYRO_FILTER_LENGTH 1

// TODO: Measure
#define DRIVE_WIDTH 15
#define DISTANCE_FRONT_LEFT_DRIVE_WHEEL_CENTER 7.5
#define DISTANCE_BACK_LEFT_DRIVE_WHEEL_CENTER 7.5
#define DISTANCE_FRONT_RIGHT_DRIVE_WHEEL_CENTER 7.5
#define DISTANCE_BACK_RIGHT_DRIVE_WHEEL_CENTER 7.5
#define AVG_DRIVETRAIN_RADIUS (DISTANCE_FRONT_LEFT_DRIVE_WHEEL_CENTER + DISTANCE_BACK_LEFT_DRIVE_WHEEL_CENTER + DISTANCE_FRONT_RIGHT_DRIVE_WHEEL_CENTER + DISTANCE_BACK_RIGHT_DRIVE_WHEEL_CENTER) / 4

#else

#define DRIVE_WHEEL_DIAMETER 3.25
#define TRACKING_WHEEL_DIAMETER 2.
#define DEGREES_PER_REVOLUTION 360.0
#define INITIAL_ODOMETRY_X 0.0
#define INITIAL_ODOMETRY_Y 0.0
#define INITIAL_ODOMETRY_THETA 0.0
#define DISTANCE_LEFT_TRACKING_WHEEL_CENTER 7.87
#define DISTANCE_RIGHT_TRACKING_WHEEL_CENTER 7.87
#define DISTANCE_BACK_TRACKING_WHEEL_CENTER 6.25
#define GYRO_ENABLED false
#define GYRO_CONFIDENCE 1.0
#define GYRO_FILTER_LENGTH 1

#define DRIVE_WIDTH 17.5
#define MAX_ACCELERATION 300
#define DEFAULT_INITIAL_SPEED 15
#define DEFAULT_FINAL_SPEED 0
#define MAX_SPEED (200.0 * M_PI * DRIVE_WHEEL_DIAMETER / 60.0 * 3.0)

#endif

#endif  // AON_CONSTANTS_HPP_
